{% set name = "jupyterhub-terraformspawner" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a05ce72aa88f8d8dfb6ce2da1ed9a416cb9af2d13e381b7f6e002e6c960cf225

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - terraformspawner = terraformspawner.cli:cli
    
requirements:
  host:
    - python >=3.3
    - pip
  run:
    - python >=3.3
    - jinja2
    - jupyterhub >=0.9.6,<1

test:
  imports:
    - terraformspawner
  commands:
    - terraformspawner

about:
  home: https://github.com/sodre/terraformspawner
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Spawn JupyterHub single-user servers with Terraform'

  doc_url: https://github.com/sodre/terraformspawner
  dev_url: https://github.com/sodre/terraformspawner

extra:
  recipe-maintainers:
    - sodre
    - ericcina
