travis:
  secure:
    BINSTAR_TOKEN: TSK9AkWo51Fih8X8vrsKDA5yJteMmKg6u5pPZ/810bqjZG2UhYYtFwdqfqI7+BumSrf3uziyyEiQ3qmW2nmda8AqkTsYz/7fulc1EPD6qe+AiuGWoOP+4MuIwGEHvimSWKXGjWSfwTT4o55AHrEqj1PD3Zc8eZEPFWX/1w8SqgGpmDDb8OJP+IjEr5HQJC38uRIwOwbmUhfmk5tGPW50RuZ5GSIU0Uuik217pnbr5Zkc9htYpY5LOoqt1QLzfciLoGpmTRxn1khKzAenDg+6AEyiWWdeiQpiVVFapGul8MjAiMBpelXnyWeVi7b+gCo6tfjnYsqRSauaGBa0Wy0zUJb8XOIeVtqsebQ53a8XIZ2KMkMiECA6T/pF164tkNn+bMmooG7cFNq++B4G5I3CEnQaMAfnXB6Y7Tbec5M3KZKeUoUiclb8723fNGvedOrcjFgY9LJTw8akOIMFpakgFzgvizhXm7jtBuniVwYz6/CN3gTB95VgB42SE+ezwhuxgImeMUwB6yoXjZZ02f+NZYf2UuoH7lvSVPQzW5nBi2Lqr4oU1vKMcHBGY2rDuouP6qSSfXnCAVUGhRmIsTGtNvPEn99gcgIprVCbUKe5EyOLjZSvfBPzl8B0MGx1yjzQ+hwS9E9cJ00TPsen1Qd3ime1w94UWxC7hnEI4NAZS8g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
